export const shopCategories = [
  { value: 'beauty', label: 'Beauty & Personal Cares' },
  { value: 'clothing', label: 'Clothing and Apparel' },
  { value: 'electronics', label: 'Electronics & Gadgets' },
  { value: 'flowers', label: 'Flowers & Gifts' },
  { value: 'food', label: 'Food & Beverages' },
  { value: 'groceries', label: 'Groceries' },
  { value: 'gifts', label: 'Gifts & Stationery' },
  { value: 'health', label: 'Health & Wellness' },
  { value: 'home', label: 'Home & Garden' },
  { value: 'jewelry', label: 'Jewelry & Accessories' },
  { value: 'kids', label: 'Kids & Baby' },
  { value: 'music', label: 'Music & Instruments' },
  { value: 'pets', label: 'Pets & Pet Supplies' },
  { value: 'sports', label: 'Sports & Outdoors' },
  { value: 'stationery', label: 'Stationery & Office Supplies' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'travel', label: 'Travel & Luggage' },
  { value: 'other', label: 'Other' },
];
